-- 1. Members Table (Uses text ID because your app uses custom IDs like 'TEMP-123')
create table public.members (
  id text primary key,
  created_at timestamptz default now(),
  name text not null,
  role text default 'MEMBER',
  status text default 'PENDING',
  class text not null,
  roll text not null,
  mobile text not null,
  "fatherName" text,
  "motherName" text,
  "presentAddress" text,
  "permanentAddress" text,
  "birthCertNo" text,
  dob text,
  "bloodGroup" text,
  password text not null
);

-- 2. Projects Table
create table public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  title text not null,
  description text,
  image text,
  status text default 'ONGOING',
  researchers text[] default '{}'::text[]
);

-- 3. Announcements Table
create table public.announcements (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  title text not null,
  description text,
  date text not null,
  type text default 'PUBLIC',
  priority text default 'NORMAL'
);

-- 4. Gallery Table
create table public.gallery (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  title text not null,
  image text not null,
  category text default 'Event'
);

-- 5. Weekly Fact Table (Single Row usually)
create table public.weekly_fact (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  title text not null,
  content text not null
);

-- Enable RLS (Allow all public access for now - simpler for initial migration)
alter table public.members enable row level security;
alter table public.projects enable row level security;
alter table public.announcements enable row level security;
alter table public.gallery enable row level security;
alter table public.weekly_fact enable row level security;

create policy "Enable all access for members" on public.members for all using (true) with check (true);
create policy "Enable all access for projects" on public.projects for all using (true) with check (true);
create policy "Enable all access for announcements" on public.announcements for all using (true) with check (true);
create policy "Enable all access for gallery" on public.gallery for all using (true) with check (true);
create policy "Enable all access for weekly_fact" on public.weekly_fact for all using (true) with check (true);

-- Insert Default Admin (Matches your db.ts seed)
insert into public.members (
  id, role, status, name, class, roll, mobile, password, "presentAddress"
) values (
  '1234567890', 'ADMIN', 'APPROVED', 'Chief Admin', 'Staff', '00', '01700000000', 'qwertyuiop', 'School Administration'
) on conflict (id) do nothing;

-- Insert Default Weekly Fact
insert into public.weekly_fact (title, content) 
values ('Weekly Fact: Quantum Entanglement', 'Did you know? When two particles become entangled...')
on conflict do nothing;
